
#pragma once

#define WERROR_ERROR_GENERIC         0
#define WERROR_SUCCESS               1
#define WERROR_WARNING_ALREADYOPEN   16
#define WERROR_ERROR_OUTOFMEMORY     128
#define WERROR_ERROR_INVALIDARG      129
#define WERROR_ERROR_INVALIDSTATE    130
#define WERROR_ERROR_INVLAIDSIZE     131
#define WERROR_ERROR_ITEMNOTFOUND    132
#define WERROR_ERROR_NOTSUPPFEATURE  133
#define WERROR_ERROR_TIMEOUT         134
#define WERROR_ERROR_INVALIDRESP     135
#define WERROR_ERROR_CORRUPTEDDATA   136
#define WERROR_ERROR_INVALIDVER      137
